#!/usr/bin/env bash
# generate-compose.sh — reads .env, produces docker-compose.yaml with range support
set -euo pipefail
cd "$(dirname "$0")"

# ── load .env (existing env vars take precedence over .env) ──
if [ -f .env ]; then
  while IFS='=' read -r key val || [ -n "$key" ]; do
    [[ "$key" =~ ^[[:space:]]*# ]] && continue
    [ -z "${key// }" ] && continue
    key="${key// /}"; val="${val# }"
    [ -z "${!key:-}" ] && export "$key=$val"
  done < .env
fi

# ── expand RUNNER_RANGE into a list of IDs ──
expand_range() {
  local range="$1" item first last i
  IFS=',' read -ra parts <<< "$range"
  for item in "${parts[@]}"; do
    if [[ "$item" == *-* ]]; then
      first="${item%-*}"; last="${item#*-}"
      for ((i=first; i<=last; i++)); do echo "$i"; done
    else
      echo "$item"
    fi
  done
}

IDS=( $(expand_range "${RUNNER_RANGE}") )

PREFIX="${RUNNER_NAME_PREFIX:-runner}"
VPREFIX="${VOLUME_NAME_PREFIX:-runner-data}"
CPUS="${RUNNER_CPUS:-4}"
MEM="${RUNNER_MEMORY:-8G}"
LABELS="${RUNNER_LABELS:-self-hosted,linux,x64,docker}"
GROUP="${RUNNER_GROUP:-Default}"

# ── build yaml ──
{
cat <<YAML
# Auto-generated by generate-compose.sh — do not edit manually.

x-runner-base: &runner-base
  build:
    context: .
    dockerfile: Dockerfile
  environment: &runner-env
    RUNNER_SCOPE: org
    ORG_NAME: \${ORG_NAME}
    RUNNER_TOKEN: \${RUNNER_TOKEN}
    LABELS: ${LABELS}
    RUNNER_GROUP: ${GROUP}
    DISABLE_AUTO_UPDATE: "true"
    RUN_AS_ROOT: "true"
    DISABLE_AUTOMATIC_DEREGISTRATION: "true"
    CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner-data
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pgrep -f 'Runner.Listener' || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 60s
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "3"
  deploy:
    resources:
      limits:
        cpus: '${CPUS}'
        memory: ${MEM}

services:
YAML

for id in "${IDS[@]}"; do
cat <<YAML
  ${PREFIX}-${id}:
    <<: *runner-base
    environment:
      <<: *runner-env
      RUNNER_NAME: \${RUNNER_NAME_PREFIX:-${PREFIX}}-${id}
      RUNNER_WORKDIR: /tmp/runner/work-${id}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - \${VOLUME_NAME_PREFIX:-runner-data}-${id}:/runner-data
YAML
done

echo ""
echo "volumes:"
for id in "${IDS[@]}"; do
  echo "  \${VOLUME_NAME_PREFIX:-runner-data}-${id}:"
done
} > docker-compose.yaml

echo "✓ docker-compose.yaml generated with ${#IDS[@]} runners: ${IDS[*]}"
